import { server } from "@passwordless-id/webauthn";
import { CredentialKey } from "@passwordless-id/webauthn/dist/esm/types";

async function serverAuthentication(authentication:any, publicId:string) {
    const expected = {
        challenge: "56535b13-5d93-4194-a282-f234c1c24500", // whatever was randomly generated by the server.
        origin: "http://localhost:8080",
        userVerified: true, // should be set if `userVerification` was set to `required` in the authentication options (default)
        counter: 123 // Optional. For device-bound credentials, you should verify the authenticator "usage" counter increased since last time.
    }

    const credentialKey:CredentialKey = {
        id: "",
        publicKey: "",
        algorithm: "RS256"
    };

    const authenticationParsed = await server.verifyAuthentication(authentication, credentialKey, expected)
}

